### ISSUE TITLE
floats in restraints file

### ISSUE THREAD

**Issue by mieczyslaw** [haddocking/haddock-tools#19]
@amjjbonvin @JoaoRodrigues I have noticed that `restrain_bodies.py` after defining contact names, adds a distance then `0.0` and `0.0`.  `restrain_ligands.py` does similarly, but adds `1.0 1.0` after distance. For `active-passive-to-ambig.py` three floats `2.0 2.0 2.0` are hardcoded (so no real distance information?).

1) Are those floats in use by CNS? If so, what's the meaning of distance=2.0 for ambig restraints? 
2) Do 0.0, 1.0, 2.0 mean anything or this is only to match a format?
3) Can ambiguous restraints be created between small molecules as well or only between protein or DNA chains?

Thanks.

**Comment by JoaoRodrigues** [comment]
Hi @mieczyslaw 

The distance restraint syntax is `assign sele1 sele2 targetD lowerBound upperBound`. In restraint bodies, we use 0 0 for the two last values because we have exact distances we want to keep between two atoms. For the ligand, it's the same, but I assume you want some wiggle room. For ambiguous restraints, that 2 2 2 means 0-4A which is fairly reasonable given the nature of the restraints (sort of averaged over all pairs of atoms between the two residues.

**Comment by JoaoRodrigues** [comment]
And yes, they can be used between anything and anything. Have a look at https://cns-online.org - tutorials.

**Comment by amjjbonvin** [comment]
Also refer to our Nature Protocol paper, box 4 if correct.

And I also showed some example in my last BioExcel webinar

https://www.youtube.com/watch?v=9dWdaJ5jBqo <https://www.youtube.com/watch?v=9dWdaJ5jBqo>

The default ambiguous distance restraint range used by the server is 2A upper limit, 0A lower limit (i.e. 2.0 2.0 0.0).
This is because of the high ambiguity, the effective distance is always shorter than any of the individual distances.

**Comment by amjjbonvin** [comment]
Should rather be 2.0 2.0 0.0

**Comment by mieczyslaw** [comment]
Thanks guys!

@JoaoRodrigues, for ligands it isn't the same, there is 1.0 1.0:
```
assi (segid B     and resi  380 and name "N"   )
     (segid B     and resi 1502 and name "O1"  )  2.813 1.0 1.0

```
According to your explanation, if this is unambigous restraint, it should be `2.813 0.0 0.0`? Is that a bug in `restrain_ligands.py`?

**Comment by amjjbonvin** [comment]
It all depends on how tightly you want to restrain your ligand. If you wan the exact distance, then yes 2.813 1.0 1.0

As define now it allows +/- 1A around 2.813

**Comment by JoaoRodrigues** [comment]
>For the ligand, it's the same, but I assume you want some wiggle room.

:) That +/- 1.0A is my wiggle room!

@mieczyslaw I warn you, CNS is a deep deep rabbit hole.

**Comment by mieczyslaw** [comment]
Thanks! I like that we have lower and upper, so we can have uneven range around the target!

Don't you think that those lower/upper should be an optional parameter rather than hardcoded only?

**Comment by mieczyslaw** [comment]
Also, for selecting from ambig ones, is that always random 50% taken (which can be switched off so 100% is used), or another percentage can be set? Is that 50% of single residue-residue contact, or (as in the format) 50% of `assign` statements?

**Comment by JoaoRodrigues** [comment]
It's 50% of the assign statements. Any other percentage can be set although the serve used to deal with fractions instead (2 - 50%), which is a bit confusing. The bioinformatics interface of the serve has a much higher removal rate (87.5% if I recall correctly).

**Comment by mieczyslaw** [comment]
Thank @JoaoRodrigues! I suppose this is a part of run.cns I should patch:
```
{* Do you want to randomly exclude a fraction of the ambiguous restraints (AIRs)? *}
{+ choice: true false +}
{===>} noecv=true;

{* Number of partitions for random exclusion (%excluded=100/number of partitions)? *}
{===>} ncvpart=2;

```

**Comment by amjjbonvin** [comment]
Yes

**Comment by amjjbonvin** [comment]
You can even generate a custom restraint file for each model. Those should be placed in `structures/it0` and be called `ambiguous.tbl_X` where X is the model number. For this to work `noecv` must be set to `false`

**Comment by mieczyslaw** [comment]
It is pretty obvious for unambiguous restraints what is the distance as atoms are mentioned.

For ambiguous restraints, what is the meaning of the distance? Is that between centroids of the residues? Backbones only? Including hydrogen atoms?

**Comment by amjjbonvin** [comment]
HADDOCK calculates the effective distance as [Sum(1/r**6)]**-1/6  

I.e. the sum of all individual 1/distances**6 between all atoms in the two selections and then takes the inverse sixth root of it.
The resulting distance is always shorter than the shortest distance entering the sum

**Comment by mieczyslaw** [comment]
Thanks for explaining all of that to me! As there is no need to add an optional parameter to the scripts, we can close this issue.
