### ISSUE TITLE
restrain_ligand.py & restrain_bodies.py not compatible with Python 3

### ISSUE THREAD

**Issue by mieczyslaw** [haddocking/haddock-tools#20]
I am using the newest version at 9a08ad3. I noticed that restrain_ligand.py & restrain_bodies.py crash with Python 3.8.5 (was working fine with Python2):

1. Syntax error:
```
File "/haddock-tools/restrain_ligand.py", line 23
    except ImportError, e:
```

2. When above corrected (with 'as'), the next one would be:
```
File "haddock-tools/restrain_ligand.py", line 62, in <module>
    ligand_com = np.asarray(ligand_com, dtype=np.float32)
  File /lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'map'
```

3. Can't compare integer and None (when verbose not given):
```
File "haddock-tools/restrain_bodies.py", line 193, in <module>
    elif args.verbose > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

New issues may come out when those above are corrected. This is required to make it compatible with HADDOCK 2.5.

**Comment by mieczyslaw** [comment]
Should I have a go on this one @amjjbonvin @rvhonorato @JoaoRodrigues ?

**Comment by amjjbonvin** [comment]
The haddock-tools have indeed never be ported to python3. So please do.
We then have to update the requirements if they only work with python3

**Comment by rvhonorato** [comment]
I see that there are a few ancestral `pdb_tools` scripts here, since the [current version](https://github.com/haddocking/pdb-tools) it is py2.7+ and 3.x compatible maybe they could be added as a submodule instead?

**Comment by mieczyslaw** [comment]
@amjjbonvin Can you please give me the permissions for `haddock-tools` so I can create a new branch `feature/python3_port`? Currently: 
```
remote: Permission to haddocking/haddock-tools.git denied to mieczyslaw.
fatal: unable to access 'https://github.com/haddocking/haddock-tools/': The requested URL returned error: 403
```

**Comment by amjjbonvin** [comment]
Those are not the same, rather old scripts if I am correct.

I.e. different from the PDB tools ones

I would not complicate things with submodules for end users (the repo is open)

**Comment by mieczyslaw** [comment]
> I would not complicate things with submodules for end users (the repo is open)

Fully agree with you @amjjbonvin ; submodules are too complicated, especially when someone is at `git clone` level of experience.
