### ISSUE TITLE
HADDOCK local crashing during run. 

### ISSUE THREAD

**Issue by iamysk** [haddocking/haddock-tools#26]
I am running haddock-local iteratively for around 100 protein-protein complexes. After a few successful docking runs, the terminal freezes with the following error. 

Pls share a possible solution. Thanks.

```
calculating structure 190
      queue command:
      /bin/csh MARK3_run11_it1_refine_190.job
Exception in thread Thread-1193:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/DATA/yogesh/alphaCov/haddock/haddock2.4-2021-05/Haddock/Main/QueueThread.py", line 10, in runqueuecommand
    process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1216, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/usr/lib64/python2.7/subprocess.py", line 1168, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by amjjbonvin** [comment]
Most like a Python limitation.

It is probably more efficient to run fewer complexes at the same time rather than starting all 100 at the same time.

**Comment by mieczyslaw** [comment]
It means that the number of system's file descriptors in use exceeds the limit. This can be changed with 'ulimit' in linux.

It may also be an issue with the code when files are not closed, or temporary files are created on low level (I created a bug report to Python developers as the tempfile documentation doesn't mention that when creating a temporary file, it should be both removed after use and file descriptor closed even though the file was never opened).

**Comment by iamysk** [comment]
> Most like a Python limitation. It is probably more efficient to run fewer complexes at the same time rather than starting all 100 at the same time.

Thanks for the suggestion @amjjbonvin . I am not running 100 complexes simultaneously. My setup looks like the following.

```
# Input PDB directory
set z="processed_pdb_batch2/*"

@ run=1
# Iterate over all the proteins in the directory
foreach i (`ls -d $z`)
 # Make run.param file for current complex
 python makeParam.py --pdb $i --run $run
 # 1st haddock initialization
 haddock2.4
 # Enter run directory
 cd run$run
 # Edit the run.cns file to use 128 cores
 python ../editCNS.py --filename run.cns
 # 2st haddock initialization
 haddock2.4
 cd ..
 @ run+=1
 echo $i
 echo $run
end
```
It runs well for the initial few complexes, but arbitrarily freezes with the mentioned error or skips the current run and moves over to the next complex (Inferred from the small size ~400MB of such run directory in comparison to a complete run that weighs exactly 1.1GB). I suspect some temp files are not being closed properly during the three step (it0, it1, water) docking process for these incomplete runs, leading to the eventual bottleneck. Pls suggest a way to overcome or an alternative to automate HADDOCK runs for multiple complexes.

Thanks.

**Comment by amjjbonvin** [comment]
This is really an issue of your system and not haddock.
We are running on our server behind the web portal up to 125 // docking runs without running into those issues.
Most files are created and written by CNS and not python.

**Comment by amjjbonvin** [comment]
May-be interesting for your case: https://github.com/haddocking/haddock-pilot <https://github.com/haddocking/haddock-pilot>

Work in progress.
