### ISSUE TITLE
Please consider publishing `haddock-tools` as a `conda`/`pip` package

### ISSUE THREAD

**Issue by antonkulaga** [haddocking/haddock-tools#27]
I think it will be convenient if you publish at conda-forge (or bioconda) or pip

**Comment by amjjbonvin** [comment]
@rvhonorato @joaomcteixeira may-be an idea to include the relevant scripts into a `tools` folder of haddock3? Or should we keep this a separate repo (no longer needed for haddock3+)

**Comment by joaomcteixeira** [comment]
If we include them in a `tools/` folder we are not making them part of the haddock3 pip package. We can double-check which are the most relevant after https://github.com/haddocking/haddock3/pull/144 and have them also as haddock3 main CLIs. But we can also include them in a `tools` folder if we see giving them `CLI` relevance is too much.

**Comment by amjjbonvin** [comment]
Ok - let’s think a bit about it then.  

In principle we could create a `tools` folder containing useful scripts without making them CLI (same as the examples folder.

**Comment by rvhonorato** [comment]
We could do that, but I think the idea of this repo is (as the name says) a collection of tools that have been developed both by the group and the community that are usable with Haddock. For us to make it a package we'd need to document every script and add tests (obviously make sure all scripts do what they should).

Since these are very-very specifics tasks, these tools here could rather be considered a starting point for your own tool development rather than out-of-shelf tools (think of `pdb-tools`)

Other than that, and since the core code is packaged with specific tools, either in v2 or v3 I don't see how having this specific repository would be beneficial.

**Comment by joaomcteixeira** [comment]
Rodrigo has a point here, also. Having this repository compatible with `python setup.py develop` is an easy task, but to official publish it in `pip`/`conda` raises the docs/tests/design requirements. For HADDOCK3, we do are lifting to the level of CLI those tools that deserve it. It can be that many of the tools here become refactored in HADDOCK3 and lifted to that level. HADDOCK3 is indeed prepared to be installed with `python setup.py develop`. Regarding `conda`, if the package does not require special compiled dependencies or code, there's no need to go conda (eventually).

But, above all, we do appreciate your interest in these tools. Apart from `pip`/`conda` publishing, what is it that you miss from this repository? Is it just the CLI executable availability? Or you were really trying to cheer us up to raise these to the next level? :wink:

Cheers!

**Comment by antonkulaga** [comment]
>Apart from pip/conda publishing, what is it that you miss from this repository? 

I am trying to automate antibody-antiget docking for my research. Right now I am trying to use haddock2.4 as haddock3 master is broken. Haddock2.4 tutorials are outdated in many places and require me to use pdb-tools and haddock-tools, while pdb-tools are nicely published, including haddock-tools is a headache. Overall, haddock2.4 is a nightmare experience for me: too many small scripts to run or edit, too many things to fix to make it work, outdated tutorials, and errors without explanations (when with a totally valid model generated by haddock-antibody protocol you get "prot_psf_mol1 could not be created" without any explanations you do not really what to do).

**Comment by rvhonorato** [comment]
It does not seem that we will publish `haddock-tools` soon and it will be instead distributed together with the appropriate version, either v2.4 and v3.0.

For all other questions and support @antonkulaga please go to [ask.bioexcel.eu ](https://ask.bioexcel.eu/). 😉

**Comment by amjjbonvin** [comment]
If there are problems with the tutorials, please let us know exactly what they are.

We are using these regularly and sofar did not encounter problems…

Automation is a different thing and non trivial for sure!
